apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.30
        ports:
        - containerPort: 16686  # Porta da interface web do Jaeger
        - containerPort: 6831   # Porta para UDP (Agente)
        - containerPort: 6832   # Porta para TCP (Agente)
        - containerPort: 14268  # Porta HTTP para o Coletor
        - containerPort: 14250  # Porta gRPC para o Coletor
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"  # Porta para Zipkin
        - name: MEMORY_MAX_TRACES
          value: "50000"  # Quantidade de traces que podem ser armazenados na memória

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686  # Porta da interface web do Jaeger
    targetPort: 16686
    protocol: TCP
    name: query
  - port: 6831  # Porta do agente UDP
    targetPort: 6831
    protocol: UDP
    name: agent-udp
  - port: 6832  # Porta do agente TCP
    targetPort: 6832
    protocol: TCP
    name: agent-tcp
  - port: 14268  # Porta HTTP do coletor
    targetPort: 14268
    protocol: TCP
    name: collector-http
  - port: 14250  # Porta gRPC do coletor
    targetPort: 14250
    protocol: TCP
    name: collector-grpc
  selector:
    app: jaeger
  type: ClusterIP
